In [ ]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np
import scipy as sci

In [697]:
rawData = pd.read_csv(unicode('/Users/wangrun/data/Taxi-20150401.csv', 'utf-8').encode('gbk'))

In [698]:
rawData.drop(['Unnamed: 0'],axis=1,inplace=True)

In [699]:
# rawData2 = pd.read_csv(unicode('/Users/wangrun/data/Taxi-20150402.csv', 'utf-8').encode('gbk'))
# rawData2.drop(['Unnamed: 0'],axis=1,inplace=True)

In [700]:
for i in range(2,31):
    if i<10:
        path_str = '0'+str(i)
    else:
        path_str = str(i)
    path = '/Users/wangrun/data/Taxi-201504'+path_str+'.csv'
    rawData2 = pd.read_csv(unicode(path, 'utf-8').encode('gbk'))
    rawData2.drop(['Unnamed: 0'],axis=1,inplace=True)
    rawData = rawData.append(rawData2)

In [701]:
# rawData = rawData.append(rawData2).append(rawData3)
rawData.drop(['Unnamed: 0.1'],axis=1,inplace=True)

In [734]:
a=rawData.copy()

In [735]:
rawData=a.drop_duplicates()

In [737]:
rawData

0               1  direction  hour  isWeekend  qiwen  rain  speed  \
0         92    2015-4-1-4-6         80     4          0   17.4   0.0    0.0   
92        99    2015-4-1-4-5         80     4          0   17.4   0.0    0.0   
191      136    2015-4-1-3-1         80     3          0   17.4   0.0    0.0   
327      366    2015-4-1-5-5         80     5          0   17.4   0.0    0.0   
693      368    2015-4-1-5-4         80     5          0   17.4   0.0    0.0   
1061      80    2015-4-1-4-2         80     4          0   17.4   0.0    0.0   
1141     103    2015-4-1-3-4         80     3          0   17.4   0.0    0.0   
1244     263    2015-4-1-5-3         80     5          0   17.4   0.0    0.0   
1507      68    2015-4-1-4-4         80     4          0   17.4   0.0    0.0   
1575     105    2015-4-1-3-3         80     3          0   17.4   0.0    0.0   
1680      82    2015-4-1-4-3         80     4          0   17.4   0.0    0.0   
1762      84    2015-4-1-3-6         80     3          0   17.4   0.0    0.0   
1846     493    2015-4-1-5-6         80     5          0   17.4   0.0    0.0   
2339      81    2015-4-1-3-5         80     3          0   17.4   0.0    0.0   
2420     211    2015-4-1-5-2         80     5          0   17.4   0.0    0.0   
2631     118    2015-4-1-3-2         80     3          0   17.4   0.0    0.0   
2749      75    2015-4-1-4-1         80     4          0   17.4   0.0    0.0   
2824     170    2015-4-1-5-1         80     5          0   17.4   0.0    0.0   
2994     656    2015-4-1-0-4         80     0          0   19.4   0.0    0.0   
3650     920    2015-4-1-0-1         80     0          0   19.4   0.0    0.0   
4570     465    2015-4-1-1-2         80     1          0   19.4   0.0    0.0   
5035     711    2015-4-1-0-3         80     0          0   19.4   0.0    0.0   
5746     532    2015-4-1-0-6         80     0          0   19.4   0.0    0.0   
6278     170    2015-4-1-2-5         80     2          0   19.4   0.0    0.0   
6448     404    2015-4-1-1-3         80     1          0   19.4   0.0    0.0   
6852     265    2015-4-1-2-1         80     2          0   19.4   0.0    0.0   
7117     896    2015-4-1-0-2         80     0          0   19.4   0.0    0.0   
8013     312    2015-4-1-1-5         80     1          0   19.4   0.0    0.0   
8325     350    2015-4-1-1-4         80     1          0   19.4   0.0    0.0   
8675     534    2015-4-1-1-1         80     1          0   19.4   0.0    0.0   
...      ...             ...        ...   ...        ...    ...   ...    ...   
208880  2517  2015-4-30-19-2         97    19          0   19.6   0.0    2.4   
211397  2509  2015-4-30-19-1         97    19          0   19.6   0.0    2.4   
213906  2242  2015-4-30-18-3         97    18          0   19.6   0.0    2.4   
216148  2395  2015-4-30-18-5         97    18          0   19.6   0.0    2.4   
218543  2647  2015-4-30-20-2         97    20          0   19.6   0.0    2.4   
221190  2280  2015-4-30-18-1         97    18          0   19.6   0.0    2.4   
223470  2675  2015-4-30-20-1         97    20          0   19.6   0.0    2.4   
226145  2364  2015-4-30-18-6         97    18          0   19.6   0.0    2.4   
228509  2686  2015-4-30-20-3         97    20          0   19.6   0.0    2.4   
231195  2348  2015-4-30-18-4         97    18          0   19.6   0.0    2.4   
233543  2693  2015-4-30-20-6         97    20          0   19.6   0.0    2.4   
236236  2565  2015-4-30-19-3         97    19          0   19.6   0.0    2.4   
238801  1444  2015-4-30-23-5         95    23          0   16.2   0.0    2.7   
240245  2286  2015-4-30-22-3         95    22          0   16.2   0.0    2.7   
242531  1303  2015-4-30-23-6         95    23          0   16.2   0.0    2.7   
243834  1576  2015-4-30-23-4         95    23          0   16.2   0.0    2.7   
245410  1925  2015-4-30-22-6         95    22          0   16.2   0.0    2.7   
247335  2216  2015-4-30-22-4         95    22          0   16.2   0.0    2.7   
249551  266

In [738]:
train_x_index=['hour','isWeekend','qiwen','speed','rain','time_div']

In [739]:
from sklearn.cross_validation import train_test_split
#x为数据集的feature熟悉，y为label.
x_train, x_test, y_train, y_test = train_test_split(rawData[train_x_index], rawData['0'], test_size = 0.3)

In [740]:
# Train_x = rawData[train_x_index].as_matrix()

In [741]:
x_train.shape

(3024, 6)

In [742]:
# Train_x.shape

In [743]:
# train_y = rawData['0'].as_matrix()

In [744]:
y_train.shape

(3024,)

In [745]:
from sklearn.ensemble import RandomForestRegressor

In [746]:
rnd_clf = RandomForestRegressor()
rnd_clf.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [747]:
pre = rnd_clf.predict(x_test)

In [748]:
pre

array([ 2554.6,    80.2,  2217.4, ...,  2797.7,  2547.3,   405.3])

In [749]:
y_test

325990    2552
84022       65
115213    2386
232658    2455
85944       97
31589     2371
254765    1341
100934    2998
64320     2846
248564    1521
112188    2402
274731    2068
199884    2264
46743     2644
121114    3017
41810      122
129614    2326
393499    1285
76631     2325
95393      828
83160       90
159806    2384
98350     2711
105146    2500
134081     201
90886      379
134401      84
45718     1988
27886     2201
119958    2886
          ... 
60578     2372
97342     2554
121533    2580
49208      177
6651        87
229018    2620
26547     2102
28139      793
171941    2456
165184    2812
186392    2502
82679     2939
32103       85
182847    2859
18044     2326
272920    2777
239191    2561
117121    2885
282109    1744
100604    2594
4761       236
93202     2754
48990      487
82979       67
63325     2939
29216     2535
44980     2368
163590    2525
173693    2612
4875       365
Name: 0, Length: 1296, dtype: int64

In [750]:
pre.reshape(-1,1)

array([[ 2554.6],
       [   80.2],
       [ 2217.4],
       ..., 
       [ 2797.7],
       [ 2547.3],
       [  405.3]])

In [751]:
def cal_score(pre,y):
    cost = np.sqrt(np.power((pre-y),2))
    return cost

In [752]:
cost = cal_score(pre,y_test)
print np.mean(cost)

75.7594907407


In [753]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rnd_clf,pre.reshape(-1,1),y_test.reshape(-1,1),cv=5,scoring="neg_mean_squared_error")
rmse_scores = np.sqrt(-scores)

/Users/wangrun/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  


In [754]:
np.mean(rmse_scores)

149.08817094781506

In [755]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='gini')
clf = clf.fit(x_train, y_train)

In [756]:
tree_cost = clf.predict(x_test)

In [757]:
# print np.mean(tree_cost)
tree_cost.reshape(-1,1)

array([[2371],
       [  74],
       [2439],
       ..., 
       [2753],
       [2595],
       [ 382]])

In [758]:
print y_test

325990    2552
84022       65
115213    2386
232658    2455
85944       97
31589     2371
254765    1341
100934    2998
64320     2846
248564    1521
112188    2402
274731    2068
199884    2264
46743     2644
121114    3017
41810      122
129614    2326
393499    1285
76631     2325
95393      828
83160       90
159806    2384
98350     2711
105146    2500
134081     201
90886      379
134401      84
45718     1988
27886     2201
119958    2886
          ... 
60578     2372
97342     2554
121533    2580
49208      177
6651        87
229018    2620
26547     2102
28139      793
171941    2456
165184    2812
186392    2502
82679     2939
32103       85
182847    2859
18044     2326
272920    2777
239191    2561
117121    2885
282109    1744
100604    2594
4761       236
93202     2754
48990      487
82979       67
63325     2939
29216     2535
44980     2368
163590    2525
173693    2612
4875       365
Name: 0, Length: 1296, dtype: int64


In [759]:
def cal_mean(pre,y):
    mean1 = np.mean(1-abs(pre-y)/y)
    return mean1

In [760]:
sjslmean = cal_mean(pre,y_test)
print sjslmean

0.931498581122


In [761]:
jcsmean = cal_mean(tree_cost,y_test)
print jcsmean

0.888253335485
